### ISSUE TITLE
I have got error in low internet connection state

### ISSUE THREAD

**Issue by lokesh-univest** [smallcase/gw-mob-sdk-flutter#29]
I have got following error in low internet connection state. This error increase errors in my Crashlytics. I am using latest version of scgateway_flutter_plugin

Error:

```
W/System.err(21156): java.net.UnknownHostException: Unable to resolve host "config.smallcase.com": No address associated with hostname
W/System.err(21156): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
W/System.err(21156): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/System.err(21156): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/System.err(21156): 	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
W/System.err(21156): 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
W/System.err(21156): 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
W/System.err(21156): 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
W/System.err(21156): 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
W/System.err(21156): 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
W/System.err(21156): 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
W/System.err(21156): 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
W/System.err(21156): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
W/System.err(21156): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err(21156): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
W/System.err(21156): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err(21156): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
W/System.err(21156): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err(21156): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
W/System.err(21156): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err(21156): 	at com.example.g1$a.intercept(ConfigNetworkModule.kt:6)
W/System.err(21156): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
W/System.err(21156): 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
W/System.err(21156): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517
```

**Comment by indrajit-roy-sc** [comment]
Hi Lokesh

Are you able to open https://config.smallcase.com/gateway/copyConfig/production/copyConfig.json in your browser?

**Comment by lokesh-univest** [comment]
YES, But at slow internet condition not.

**Comment by indrajit-roy-sc** [comment]
How slow are we talking here? What's the average bandwidth speed? Can you attach a screen recording?

P.S. : We don't actively track issues on GitHub at the moment. You would receive faster responses over mail. Thanks.
