### ISSUE TITLE
Not able to upgrade my Android to API 34

### ISSUE THREAD

**Issue by lokesh-univest** [smallcase/gw-mob-sdk-flutter#31]
When i am upgrade to API 34 in android version, its show me a crash:

```
E/AndroidRuntime(32315): java.lang.IllegalArgumentException: Unable to create call adapter for interface retrofit2.Call
E/AndroidRuntime(32315):     for method m0.b
E/AndroidRuntime(32315): 	at retrofit2.Utils.methodError(Utils.java:54)
E/AndroidRuntime(32315): 	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:116)
E/AndroidRuntime(32315): 	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:67)
E/AndroidRuntime(32315): 	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
E/AndroidRuntime(32315): 	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
E/AndroidRuntime(32315): 	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
E/AndroidRuntime(32315): 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
E/AndroidRuntime(32315): 	at $Proxy6.b(Unknown Source)
E/AndroidRuntime(32315): 	at com.smallcase.gateway.data.ConfigRepositoryImp.getBrokerConfigs(ConfigRepositoryImp.kt:1)
E/AndroidRuntime(32315): 	at com.smallcase.gateway.data.ConfigRepositoryImp.access$getBrokerConfigs(ConfigRepositoryImp.kt:1)
E/AndroidRuntime(32315): 	at com.smallcase.gateway.data.ConfigRepositoryImp$loadConfigData$1.invokeSuspend(ConfigRepositoryImp.kt:3)
E/AndroidRuntime(32315): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/AndroidRuntime(32315): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
E/AndroidRuntime(32315): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8a520f2, Dispatchers.IO]
E/AndroidRuntime(32315): Caused by: java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
E/AndroidRuntime(32315): 	at retrofit2.DefaultCallAdapterFactory.get(DefaultCallAdapterFactory.java:42)
E/AndroidRuntime(32315): 	at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:253)
E/AndroidRuntime(32315): 	at retrofit2.Retrofit.callAdapter(Retrofit.java:237)
E/AndroidRuntime(32315): 	at retrofit2.HttpServiceMethod.createCallAdapter(HttpServiceMethod.java:114)
E/AndroidRuntime(32315): 	... 17 more
```

**Comment by indrajit-roy-sc** [comment]
Hi Lokesh. Apologies for the late response. We don't actively track issues on GithHub right now.
Try adding the below pro guard rules to your app if not already resolved.

```
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

##---------------End: proguard configuration for Gson  ----------

##---------------Begin: proguard configuration for Retrofit  ----------

-keep class retrofit2.** { *; }
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }

-keep class androidx.lifecycle.LiveData { *; }

# Retrofit does reflection on generic parameters. InnerClasses is required to use Signature and
# EnclosingMethod is required to use InnerClasses.
-keepattributes Signature, InnerClasses, EnclosingMethod

# Retrofit does reflection on method and parameter annotations.
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

# Keep annotation default values (e.g., retrofit2.http.Field.encoded).
-keepattributes AnnotationDefault

# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*

# With R8 full mode, it sees no subtypes of Retrofit interfaces since they are created with a Proxy
# and replaces all potential values with null. Explicitly keeping the interfaces prevents this.
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>

# Keep inherited services.
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface * extends <1>

# With R8 full mode generic signatures are stripped for classes that are not
# kept. Suspend functions are wrapped in continuations where the type argument
# is used.
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation

# R8 full mode strips generic signatures from return types if not kept.
-if interface * { @retrofit2.http.* public *** *(...); }
-keep,allowoptimization,allowshrinking,allowobfuscation class <3>

# With R8 full mode generic signatures are stripped for classes that are not kept.
-keep,allowobfuscation,allowshrinking class retrofit2.Response

##---------------End: proguard configuration for Retrofit  ----------
```
